sinks:
  - sink: stderr
    level: WARNING
    format: "<fg #7f1cdb>QiliSDK</> | <green>{time:YYYY-MM-DD at HH:mm:ss}</green> | <lvl>{level}</> | <lvl>{level.icon} {message}</>"
    filter: qilisdk
    colorize: true

intercept_libraries:
  - name: httpx
    level: ERROR
  - name: httpcore
    level: ERROR
  - name: keyring
    level: ERROR
  - name: matplotlib
    level: ERROR
